# Generated by Django 5.2.16 on 2026-07-24 20:46

import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sku',),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('sku'), name='inventory_product_sku_ci_unique', violation_error_code='duplicate_sku', violation_error_message='A product with this SKU already exists.')],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('code',),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='inventory_warehouse_code_ci_unique', violation_error_code='duplicate_warehouse_code', violation_error_message='A warehouse with this code already exists.')],
            },
        ),
    ]
