# Generated by Django 5.2.16 on 2026-08-12 11:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_create_product_and_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0)),
                ('reserved_quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.warehouse')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'warehouse'), name='inventory_stock_product_warehouse_unique'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='inventory_stock_quantity_gte_0'), models.CheckConstraint(condition=models.Q(('reserved_quantity__gte', 0)), name='inventory_stock_reserved_quantity_gte_0'), models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('quantity'))), name='inventory_stock_reserved_lte_quantity')],
            },
        ),
    ]
