# Generated by Django 5.2.16 on 2026-08-12 15:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_create_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('STOCK_INCREASE', 'Stock increase'), ('STOCK_DECREASE', 'Stock decrease'), ('RESERVATION_CREATED', 'Reservation created'), ('RESERVATION_CONFIRMED', 'Reservation confirmed'), ('RESERVATION_CANCELLED', 'Reservation cancelled'), ('RESERVATION_EXPIRED', 'Reservation expired')], max_length=32)),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_before', models.IntegerField()),
                ('quantity_after', models.IntegerField()),
                ('reserved_before', models.IntegerField()),
                ('reserved_after', models.IntegerField()),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stock')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_movement_quantity_gt_0'), models.CheckConstraint(condition=models.Q(('quantity_before__gte', 0)), name='inventory_movement_quantity_before_gte_0'), models.CheckConstraint(condition=models.Q(('quantity_after__gte', 0)), name='inventory_movement_quantity_after_gte_0'), models.CheckConstraint(condition=models.Q(('reserved_before__gte', 0)), name='inventory_movement_reserved_before_gte_0'), models.CheckConstraint(condition=models.Q(('reserved_after__gte', 0)), name='inventory_movement_reserved_after_gte_0'), models.CheckConstraint(condition=models.Q(('reserved_before__lte', models.F('quantity_before'))), name='inventory_movement_reserved_before_lte_quantity'), models.CheckConstraint(condition=models.Q(('reserved_after__lte', models.F('quantity_after'))), name='inventory_movement_reserved_after_lte_quantity')],
            },
        ),
    ]
